# Generated by Django 5.2.9 on 2025-12-25 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('tags', models.JSONField(default=list)),
                ('intro', models.TextField()),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'published'), ('shelved', 'shelved'), ('deleted', 'deleted')], default='published', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_at'], name='novels_nove_status_e67eab_idx'), models.Index(fields=['favorites_count'], name='novels_nove_favorit_22d2de_idx'), models.Index(fields=['views'], name='novels_nove_views_14b18f_idx')],
            },
        ),
    ]
