# Generated by Django 5.2.9 on 2026-01-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0002_add_chapter_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
