# Generated by Django 5.2.9 on 2025-12-25 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelviewevent',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
        migrations.AddField(
            model_name='novelviewevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['created_at'], name='analytics_l_created_2d3731_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['user', 'created_at'], name='analytics_l_user_id_b2e825_idx'),
        ),
        migrations.AddIndex(
            model_name='novelviewevent',
            index=models.Index(fields=['created_at'], name='analytics_n_created_86c7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='novelviewevent',
            index=models.Index(fields=['novel', 'created_at'], name='analytics_n_novel_i_056d99_idx'),
        ),
        migrations.AddIndex(
            model_name='novelviewevent',
            index=models.Index(fields=['user', 'created_at'], name='analytics_n_user_id_e2cee7_idx'),
        ),
        migrations.AddIndex(
            model_name='searchevent',
            index=models.Index(fields=['created_at'], name='analytics_s_created_df2559_idx'),
        ),
        migrations.AddIndex(
            model_name='searchevent',
            index=models.Index(fields=['user', 'created_at'], name='analytics_s_user_id_388038_idx'),
        ),
    ]
