# Generated by Django 5.2.9 on 2026-01-18 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelFeatureVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector_data', models.JSONField(help_text='稀疏向量: {index: value, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vector', to='novels.novel')),
            ],
            options={
                'db_table': 'novel_feature_vector',
            },
        ),
        migrations.CreateModel(
            name='NovelSimilarity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity', models.FloatField(help_text='相似度分数，范围0-1')),
                ('algorithm', models.CharField(help_text='算法类型: item_cf, content', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_a', to='novels.novel')),
                ('novel_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_b', to='novels.novel')),
            ],
            options={
                'db_table': 'novel_similarity',
                'indexes': [models.Index(fields=['novel_a', 'algorithm', '-similarity'], name='novel_simil_novel_a_0814bc_idx'), models.Index(fields=['novel_b', 'algorithm'], name='novel_simil_novel_b_61c03f_idx')],
                'constraints': [models.UniqueConstraint(fields=('novel_a', 'novel_b', 'algorithm'), name='uq_sim_novels_algo')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(help_text='推荐分数，值越大越推荐')),
                ('algorithm', models.CharField(help_text='算法类型: cf, content, hybrid', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_cache',
                'indexes': [models.Index(fields=['user', 'algorithm', '-score'], name='recommendat_user_id_08b2a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'novel', 'algorithm'), name='uq_rec_user_novel_algo')],
            },
        ),
    ]
