# Generated by Django 5.2.9 on 2026-01-25 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
        ("novels", "0003_add_source_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadHistory",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, editable=False, default=uuid.uuid4)),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                ("last_chapter", models.CharField(blank=True, default="", max_length=255)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("novel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="novels.novel")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="readhistory",
            index=models.Index(fields=["user", "last_read_at"], name="interaction_user_la_46f3fd_idx"),
        ),
        migrations.AddConstraint(
            model_name="readhistory",
            constraint=models.UniqueConstraint(fields=("user", "novel"), name="uq_read_history_user_novel"),
        ),
    ]
