# Generated by Django 5.2.9 on 2026-01-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_add_read_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='readhistory',
            new_name='interaction_user_id_35ac5d_idx',
            old_name='interaction_user_la_46f3fd_idx',
        ),
    ]
